language: python
cache: pip
python:
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - touch log.txt
  - python udemy-dl.py "$COURSE_URL" -u "$USERNAME" -p "$PASSWORD" > log.txt  && python convert.py
