language: python
cache: pip
python:
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - wget "$LIST_URL" -O list.txt -q
  - touch log.txt
  - |
    while IFS='' read -r line || [[ -n "$line" ]]; do

        # strip trailing line break
        line=$(echo $line|tr -d '\r')

        # skip comments
        if [[ $line != "#"* ]]; then
          python udemy-dl.py "$line" -u "$USERNAME" -p "$PASSWORD" > log.txt
        fi
    done < list.txt
  - python convert.py
